version: '3.9'
services: 
  auth-service:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - ACCESS_TOKEN_SIGNATURE=access_token_signature
      - REFRESH_TOKEN_SIGNATURE=refresh_token_signature
  db:
    image: postgres:15
    restart: always
    environment:
      - DATABASE_HOST=db
      - POSTGRES_DB=auth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports: 
      - "5432:5432"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - auth-service
      - db